# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StaplerSquad < Formula
  desc "Manage multiple AI terminal agents like Claude Code, Aider, Codex, OpenCode, and Amp."
  homepage "https://github.com/TylerStaplerAtFanatics/stapler-squad"
  version "1.33.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TylerStaplerAtFanatics/stapler-squad/releases/download/v1.33.0/stapler-squad_1.33.0_darwin_amd64.tar.gz"
      sha256 "cc14c8db120d0f42da0d925e6400066cc40c1d38469b6cd5da416c693a0b8e4a"

      define_method(:install) do
        bin.install "stapler-squad"
        bin.install_symlink bin/"stapler-squad" => "ssq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TylerStaplerAtFanatics/stapler-squad/releases/download/v1.33.0/stapler-squad_1.33.0_darwin_arm64.tar.gz"
      sha256 "c4f67c94565d59fff7d2b75116e2dc9a92e9ea8aa8da51a2ef7c21d9a78e8a66"

      define_method(:install) do
        bin.install "stapler-squad"
        bin.install_symlink bin/"stapler-squad" => "ssq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TylerStaplerAtFanatics/stapler-squad/releases/download/v1.33.0/stapler-squad_1.33.0_linux_amd64.tar.gz"
      sha256 "dcac802d98c80db80afc37cdd71e92199fed82e165beb9a4be53fc6985448381"
      define_method(:install) do
        bin.install "stapler-squad"
        bin.install_symlink bin/"stapler-squad" => "ssq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TylerStaplerAtFanatics/stapler-squad/releases/download/v1.33.0/stapler-squad_1.33.0_linux_arm64.tar.gz"
      sha256 "29c5cbf943b579475a26be3b77a23498c78b8433dd5ac4107a3b321331c34fb4"
      define_method(:install) do
        bin.install "stapler-squad"
        bin.install_symlink bin/"stapler-squad" => "ssq"
      end
    end
  end

  test do
    system "#{bin}/stapler-squad version"
  end
end
