# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StaplerSquad < Formula
  desc "Manage multiple AI terminal agents like Claude Code, Aider, Codex, OpenCode, and Amp."
  homepage "https://github.com/TylerStaplerAtFanatics/stapler-squad"
  version "1.40.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/TylerStaplerAtFanatics/stapler-squad/releases/download/v1.40.0/stapler-squad_1.40.0_darwin_amd64.tar.gz"
      sha256 "e2894993ca622780987f81c72abd374d68132109933b28829b2e65439013cec0"

      define_method(:install) do
        bin.install "stapler-squad"
        bin.install_symlink bin/"stapler-squad" => "ssq"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/TylerStaplerAtFanatics/stapler-squad/releases/download/v1.40.0/stapler-squad_1.40.0_darwin_arm64.tar.gz"
      sha256 "8ed82ad5125b8ba3a8ee84d718c2e3abf3bcbd07a4722b1b7bfadf85ce70e00c"

      define_method(:install) do
        bin.install "stapler-squad"
        bin.install_symlink bin/"stapler-squad" => "ssq"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/TylerStaplerAtFanatics/stapler-squad/releases/download/v1.40.0/stapler-squad_1.40.0_linux_amd64.tar.gz"
      sha256 "1914ec0ad404dbd53381b174b3a54cadb162977f5b0f32530ffc47baabb6665c"
      define_method(:install) do
        bin.install "stapler-squad"
        bin.install_symlink bin/"stapler-squad" => "ssq"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/TylerStaplerAtFanatics/stapler-squad/releases/download/v1.40.0/stapler-squad_1.40.0_linux_arm64.tar.gz"
      sha256 "6810b4998931f193a6e422e359fa90597d598702e226c26304abdac6498662af"
      define_method(:install) do
        bin.install "stapler-squad"
        bin.install_symlink bin/"stapler-squad" => "ssq"
      end
    end
  end

  test do
    system "#{bin}/stapler-squad version"
  end
end
